version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      # first, you need to create volume on your own
      # - `docker volume create mongodbdata`
      # then, to take path
      # docker volume inspect mongodbdata
      - /var/lib/docker/volumes/mongodbdata/_data:/data/db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27018:27017"
    restart: unless-stopped
    networks:
      - common

  app_events:
    build: .
    container_name: event_service
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - common

networks:
  common:
    driver: "bridge"
