version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27018:27017"
    restart: unless-stopped
    networks:
      - common

  app_events:
    build: .
    container_name: event_service
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - common

networks:
  common:
    driver: "bridge"
